### ISSUE TITLE
goatlab/firebase-emulator Docker Image not available for platform linux/amd64/v3

### ISSUE THREAD

**Issue by ccadek** [goat-io/fluent#164]
New Docker Images have been released on goatlab/firebase-emulator. However these were only provided for the linux/arm64/v8 platform. Could you please also provide Docker Images for amd64? I depend on this Docker Image in my project and building the Image by running the [Dockerfile](https://github.com/goat-io/fluent/blob/master/packages/dev/Database/Firebase/Dockerfile) has been unsuccessful so far.

## Current behavior
Running on Manjaro Linux with amd64 architecture
```bash
~/w/o/fluent/p/d/D/Firebase master 11m 29.9s ❱ docker run goatlab/firebase-emulator:1.2
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested
exec /usr/bin/firebase: exec format error
```

**Comment by goat-io** [comment]
@ccadek I re-publish the images. Now version 1.2 is AMD by default and there is an arm version as well.
Try it out en let me know if it works for you. 
Be aware that the latest version of the firebase emulator has a slightly different config file than the old one. You can check the example file in this repo

**Comment by ccadek** [comment]
Perfect, I am able to run the Docker Image without any issues! Thank you so much!
